    - name: Get kube config file
      shell: bx cs cluster-config "{{ kube_cluster_id }}"
      register: cluster_config

    - name: find cluster filename
      shell: echo "{{ cluster_config.stdout }}" | grep "{{ kube_config_dir }}" | awk -F/ '{print $NF}'
      register: config_file

    - set_fact:
        kube_config_file_name: "{{ config_file.stdout }}"

    - set_fact:
        kubeconfig_file: "{{kube_config_dir}}/{{kube_cluster_id}}/{{kube_config_file_name}}"

    - set_fact:
        kubectlCmd: "kubectl --kubeconfig {{kube_config_dir}}/{{kube_cluster_id}}/{{kube_config_file_name}}"

    - name: Get the  kubeconfig ca file name from kubeconfig
      shell: grep -i 'certificate-authority:' {{kubeconfig_file}}  | awk {'print $2'}
      register: ca_cert_file

    - set_fact:
         kube_config_ca_file_name: "{{ ca_cert_file.stdout }}"

    - set_fact:
        bluemix_default_location: "{{ lookup('env', 'HOME') }}/.bluemix/plugins/container-service/clusters/{{kube_cluster_id}}"

    - debug:
        msg: "export KUBECONFIG={{kube_config_dir}}/{{kube_cluster_id}}/{{kube_config_file_name}}"

