---
- include: ./load-vars-environment.yml
  when: load_vars_environment is undefined

- name: Deploy kubernetes resources
  hosts: localhost
  gather_facts: False

  roles:
    - { role: example_pods }
